name: Unit-Tests

# Dieser Workflow führt auf main, test und in Pull Requests die Unit-Tests aus.
# Ein erfolgreicher Lauf bedeutet, dass die Python-Abläufe ausführbar und
# konsistent sind.
'on':
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - test

# Das GITHUB_TOKEN hat Lesezugriff für dieses Repository (für Check-Out).
permissions:
  contents: read

# Gruppierung nach Pull-Request-Nummer oder Branch-Name.
concurrency:
  group: mtext-actions-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit-Tests durchführen
    runs-on: [self-hosted, linux]
    timeout-minutes: 5
    steps:
      # Lädt den aktuellen Stand des Repositories in den Arbeitsbereich
      - name: Check-Out Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Starte die Composite Action "action.yml"
      - name: action.yml ausführen
        id: automation
        uses: ./

      # Wenn actionlint zur Verfügung stehen würde, könnte man die Workflows an sich damit prüfen
      # - name: Workflow-Dateien prüfen
      #   run: actionlint

      # Startet die Testsuite
      - name: Unit-Tests ausführen
        env:
          ACTION_PATH: ${{ steps.automation.outputs.action_path }}
          PYTHONPATH: ${{ steps.automation.outputs.action_path }}/src
        run: '"${{ steps.automation.outputs.python }}" -m unittest discover -s "$ACTION_PATH/tests" -v'
